### ISSUE TITLE
Add condition to check $test is null

### ISSUE THREAD

**Issue by thedoom13** [C4tWithShell/defectdojo-action#1]
https://github.com/C4tWithShell/defectdojo-action/blob/96731a77f6b12ed1d65c2d6e674acac4657f7b96/entrypoint.sh#L125

I think you should add a condition to check if `$test` is null. In my case, the value of `$test` is null, but the condition `! [[ -z "$test" ]]` evaluates to true. As a result, the command `curl -X DELETE "$DEFECTDOJO_URL/api/v2/tests/$test/"` is still executed, leading to the error on `line 126: {"detail":"Not: command not found"}`. 

I think it should be rewritten as `if ! [[ -z "$test" || $test == null ]]`.

Other places are experiencing the same issue. For example, 

https://github.com/C4tWithShell/defectdojo-action/blob/96731a77f6b12ed1d65c2d6e674acac4657f7b96/entrypoint.sh#L46

 will not create a new product if `$product` is null.

Thanks.

**Comment by C4tWithShell** [comment]
Thanks for reporting!
I also faced the same issue this week after update

I already prepared update, I am planning to release it tmr after I will test the API calls
